---
- name: Install and configure Apache with a PHP web site
  hosts: all
  tasks:
    - name: Install Apache
      zypper:
        name: apache2

    - name: Install Apache PHP dependencies
      zypper:
        name:
          - php
          - apache2-mod_php8

    - name: Remove index.html
      file:
        name: /var/www/html/index.html
        state: absent

    - name: Put website in place
      unarchive:
        src: website.tar.gz
        dest: /srv/www/htdocs/
        owner: root
        group: root
        mode: 0644

    - name: Enable the Apache service
      service:
        name: apache2
        state: started
        enabled: true
